### PR TITLE
Fix no output if Game is not connected to TTY

### PR DESCRIPTION
**Pull request by misha-ridge**
`iface == nil` checks if interface value is nil, not if the value
it holds is nil, so stdout reporter was never added if TTY detection failed.

Related to ridge/tectonic#11387

### CODE REVIEW

**Review by feldgendler — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ridge/game/39)* status: all files reviewed; 1 unresolved discussion (waiting on @misha-ridge)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/ridge/game/39#-MsUlmHH-saEPw4XPwMo):*
Go interfaces can be nil.

What you probably wanted to say is that even a nil pointer to a concrete type, when assigned to an interface variable, results in a non-nil value of the interface type. This needs to be fixed in the PR description.

**Review by misha-ridge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ridge/game/39)* status: all files reviewed; 1 unresolved discussion (waiting on @feldgendler)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/ridge/game/39#-MsUlmHH-saEPw4XPwMo):*
<details><summary><i>Previously, feldgendler (Alexey Feldgendler) wrote…</i></summary><blockquote>

Go interfaces can be nil.

What you probably wanted to say is that even a nil pointer to a concrete type, when assigned to an interface variable, results in a non-nil value of the interface type. This needs to be fixed in the PR description.
</blockquote></details>

Values of interface type are never nil: `var a interface{}; a == nil` is never true, that's what I wrote.

**Review by feldgendler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ridge/game/39)* status: all files reviewed; 1 unresolved discussion (waiting on @misha-ridge)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/ridge/game/39#-MsUlmHH-saEPw4XPwMo):*
<details><summary><i>Previously, misha-ridge (Misha Gusarov) wrote…</i></summary><blockquote>

Values of interface type are never nil: `var a interface{}; a == nil` is never true, that's what I wrote.
</blockquote></details>

```
alexey@sandwich:~$ gore
gore version 0.2.6  :help for help
gore> var a interface{}
gore> a == nil
true
```

**Review by misha-ridge — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ridge/game/39)* status: all files reviewed; 1 unresolved discussion (waiting on @feldgendler)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/ridge/game/39#-MsUlmHH-saEPw4XPwMo):*
<details><summary><i>Previously, feldgendler (Alexey Feldgendler) wrote…</i></summary><blockquote>

```
alexey@sandwich:~$ gore
gore version 0.2.6  :help for help
gore> var a interface{}
gore> a == nil
true
```
</blockquote></details>

Done.

**Pull request merged**
