### PR TITLE
Implement uncluttered colored TTY reporter

### PR DESCRIPTION
**Pull request by dottedmag**
Print currently running/blocked tasks as a status line.

Required addional work outside of the reporter:
- Add GAMEFILE_LOGFILE to save full log to the file
- Add GAMEFILE_NO_TTY to disable TTY reporter
- Implement multiple reporters in core Game code
- Convert consoleReporter to be able to print to file

### CODE REVIEW

**Review by dottedmag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ridge/game/27)* status: 10 of 10 files unreviewed; PR check Travis CI - Pull Request failed; 1 unresolved discussion (waiting on @dottedmag and @feldgendler)

___
*[toplevel/log.go, line 1 at r1](https://reviewable.io/reviews/ridge/game/27#-MeGazT5BjyUtZ6yt1NS:-MeGazT5BjyUtZ6yt1NT:bc4s2oi) ([raw file](https://github.com/ridge/game/blob/362bc2e0d4d2af073579f32239eadaae8206958f/toplevel/log.go#L1)):*
> ```Go
> package toplevel
> ```

Moved from `toplevel/toplevel.go` with one change: `fmt.Printf(` -> `fmt.Fprintf(fr.File`

**Review by feldgendler — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ridge/game/27)* status: all files reviewed; PR check Travis CI - Pull Request failed; 4 unresolved discussions (waiting on @dottedmag)

___
*[toplevel/toplevel.go, line 353 at r1](https://reviewable.io/reviews/ridge/game/27#-MeGwM9A8nsdKXeKSu_z:-MeGwM9B0I0GLvwcAXH3:bqfm6wv) ([raw file](https://github.com/ridge/game/blob/362bc2e0d4d2af073579f32239eadaae8206958f/toplevel/toplevel.go#L353)):*
> ```Go
> 		if err != nil {
> 			panic(err)
> 		}
> ```

Can you use the `must` library here?
___
*[tty/deps.go, line 25 at r1](https://reviewable.io/reviews/ridge/game/27#-MeGwrF614N3eulstBMT:-MeGwrF71rHX_VQ3yFOF:b-tkkz5z) ([raw file](https://github.com/ridge/game/blob/362bc2e0d4d2af073579f32239eadaae8206958f/tty/deps.go#L25)):*
> ```Go
> 
> func (ds *depSet) unblock(to int) {
> 	out := []dep{}
> ```

`var out []dep`
___
*[tty/reporter_unix.go, line 219 at r1](https://reviewable.io/reviews/ridge/game/27#-MeGxtL61zFf86kLYXJ-:-MeGxtL61zFf86kLYXJ0:bwpwjyy) ([raw file](https://github.com/ridge/game/blob/362bc2e0d4d2af073579f32239eadaae8206958f/tty/reporter_unix.go#L219)):*
> ```Go
> 		for range winszCh {
> 			r.mu.Lock()
> 			defer r.mu.Unlock()
> ```

With every iteration of the loop, `r.mu.Lock` will be called again and again, while accumulating pending `r.mu.Unlock` calls to be all executed at the end of the function.

**Review by dottedmag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ridge/game/27)* status: 3 of 10 files unreviewed; 4 unresolved discussions (waiting on @feldgendler)

___
*[toplevel/toplevel.go, line 353 at r1](https://reviewable.io/reviews/ridge/game/27#-MeGwM9A8nsdKXeKSu_z:-MeH1qWG8zwJTFyHo06E:bkgrecf) ([raw file](https://github.com/ridge/game/blob/362bc2e0d4d2af073579f32239eadaae8206958f/toplevel/toplevel.go#L353)):*
<details><summary><i>Previously, feldgendler (Alexey Feldgendler) wrote…</i></summary><blockquote>

Can you use the `must` library here?
</blockquote></details>

I was too lazy. Fixed.
___
*[tty/deps.go, line 25 at r1](https://reviewable.io/reviews/ridge/game/27#-MeGwrF614N3eulstBMT:-MeH1pzKBtI2tjCXiMN0:b-896fix) ([raw file](https://github.com/ridge/game/blob/362bc2e0d4d2af073579f32239eadaae8206958f/tty/deps.go#L25)):*
<details><summary><i>Previously, feldgendler (Alexey Feldgendler) wrote…</i></summary><blockquote>

`var out []dep`
</blockquote></details>

Done.
___
*[tty/reporter_unix.go, line 219 at r1](https://reviewable.io/reviews/ridge/game/27#-MeGxtL61zFf86kLYXJ-:-MeH1tfk8eky3NN1nFo3:b-uxu52l) ([raw file](https://github.com/ridge/game/blob/362bc2e0d4d2af073579f32239eadaae8206958f/tty/reporter_unix.go#L219)):*
<details><summary><i>Previously, feldgendler (Alexey Feldgendler) wrote…</i></summary><blockquote>

With every iteration of the loop, `r.mu.Lock` will be called again and again, while accumulating pending `r.mu.Unlock` calls to be all executed at the end of the function.
</blockquote></details>

Nice catch, thanks.

This explains why one of the builds got stuck while I was testing it.

**Review by feldgendler — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ridge/game/27)* status: all files reviewed; PR check Travis CI - Pull Request failed; 2 unresolved discussions (waiting on @dottedmag)

___
*[toplevel/toplevel.go, line 355 at r2](https://reviewable.io/reviews/ridge/game/27#-MeH6kWI81t8TLHjKWz0:-MeH6kWI81t8TLHjKWz1:b6ebaja) ([raw file](https://github.com/ridge/game/blob/182c1044e5f56273be0530a1e20eaa5888557592/toplevel/toplevel.go#L355)):*
> ```Go
> 			fmt.Printf("Failed to create log file %s: %v\n", err)
> 			os.Exit(1)
> 		}
> ```

Non-blocking:

I don't see how `os.Exit` is better than a panic; and a `must` call is shorter.

**Review by feldgendler — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ridge/game/27)* status: :shipit: complete! all files reviewed; all discussions resolved

**Pull request merged**
